---
- hosts: webservers
  sudo: yes

  tasks:
  - name: ensure apache is installed
    yum: name=httpd state=present

  - name: start apache service
    service: name=httpd enables=yes state=started

  - name: stop IP tables
    service: name-iptables state=stopped
