---
- hosts: dbservers
  sudo: yes

  tasks:
  - name: ensure MySQL is installed
    yum: name=mysqld state=present

  - name: start mysql services
    service: name=mysqld state=started

  - name: stop ip tables
    service: name=iptables state=stopped 
